apiVersion: v1
kind: Service
metadata:
  name: {{ include "ethereum-tracker.svcName" . }}
  labels:
    app: {{ include "ethereum-tracker.svcName" . }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.port }}
  selector:
    app: {{ include "ethereum-tracker.appName" . }}
